name: zentoast
description: "A headless, fully customizable toast system for Flutter."
version: 0.2.0
homepage: https://github.com/definev/zentoast

environment:
  sdk: ^3.7.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  motor: ^1.1.0
  oref: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
